version: '2.1'
services:
  kimai:
    build:
      context: .
      args:
        KIMAI_VERSION: 1.3.1
        KIMAI_SHA256: cbf86e8e52bc48a1769e15301463b698f475c47201c973268c43a38efc3491ad
    ports:
      - ${EXTERNAL_PORT:-127.0.0.1:8080}:80
    restart: always
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=kimai
      - MYSQL_ROOT_PASSWORD=fKc8dlZqhNOucISGiZA6
    volumes:
      - ${DB_VOLUME:-./kimai-database}:/var/lib/mysql
    restart: always
